### ISSUE TITLE
Oct 2022

### ISSUE THREAD

**Issue by vadasambar** [vadafoss/daily-updates#1]
## What
This is an issue to update daily status on what I am doing as a member of vadafoss community. 

## How
Follow this format
```
## <3-letter-month> <2-letter-day> <4-letter-year>
### やったこと
### Problem
### Try
### TODO
### WIP
```
**やったこと**: _yatta-koto_ lit. 'things I did' in Japanese (I just find it sounds closer to what I want to say)
**Problem** (optional): problems I faced
**Try** (optional): what I am trying
**TODO** (optional): things to do
**WIP** (optional): work in progress

**Comment by vadasambar** [comment]
## Oct 28 2022
### やったこと
- added logo for vadafoss
![image](https://user-images.githubusercontent.com/34534103/198714836-1584839e-bfda-4f8f-a737-39dcde0abb3c.png)

- created https://github.com/vadafoss/.github and https://github.com/vadafoss/daily-updates repo
### TODO
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

**Comment by vadasambar** [comment]
## Oct 31 2022
### やったこと
- Looked at https://github.com/keptn/keptn.github.io/issues/1491
- Skimmed through code for [lighthouse-service](https://github.com/keptn/keptn/blob/5064ea27dc96779efbb605e908dbe5feeae27c5c/lighthouse-service) to see what changes I would have to make for supporting OpenSLO's SLO format for PoC
### WIP
- Reading https://opentelemetry.io/docs/concepts/observability-primer/
- Trying out lifecycle-controller on my local machine
- Reading about [json schema](http://json-schema.org/understanding-json-schema/)
- Reading about [schema](http://json-schema.org/understanding-json-schema/about.html#about)
- Trying out [open-feature-operator](https://github.com/open-feature/open-feature-operator) on my local k8s cluster
### Try
- Try converting the [sample SLO](https://github.com/keptn-sandbox/datadog-service/blob/8f2dcfe3109a0dcdd6c4620a5727fbf36423dfde/test/data/podtatohead.slo.yaml) in datadog-service into OpenSLO's SLO format
### TODO
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

### Problem
- I don't understand what otel does
- I don't understand [json schema](http://json-schema.org/understanding-json-schema/)
- Unable to run open-feature-operator: https://github.com/open-feature/open-feature-operator/issues/198

**Comment by vadasambar** [comment]
## Nov 1 2022
### やったこと


### WIP

### Try

### TODO


### Problem

**Comment by vadasambar** [comment]
## Nov 2 2022
### やったこと

### WIP
- Reading https://opentelemetry.io/docs/concepts/observability-primer/
- Trying out lifecycle-controller on my local machine
  - Building and deploying the operator and scheduler on my local machine
- Reading about [json schema](http://json-schema.org/understanding-json-schema/)
- Reading about [schema](http://json-schema.org/understanding-json-schema/about.html#about)

### Try
- Try converting the [sample SLO](https://github.com/keptn-sandbox/datadog-service/blob/8f2dcfe3109a0dcdd6c4620a5727fbf36423dfde/test/data/podtatohead.slo.yaml) in datadog-service into OpenSLO's SLO format
### TODO
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

### Problem
- I don't understand what otel does
- I don't understand [json schema](http://json-schema.org/understanding-json-schema/)
- Unable to run open-feature-operator: https://github.com/open-feature/open-feature-operator/issues/198
