### ISSUE TITLE
Jan 2023

### ISSUE THREAD

**Issue by vadasambar** [vadafoss/daily-updates#5]
Last month's thread: 
Dec 2022: https://github.com/vadafoss/daily-updates/issues/4

## What
This is an issue to update daily status on what I am doing as a member of vadafoss community. 

## How
Follow this format
```
## <3-letter-month> <2-letter-day> <4-letter-year>
### やったこと
### Problem
### Try
### TODO
### WIP
```
**やったこと**: _yatta-koto_ lit. 'things I did' in Japanese (I just find it sounds closer to what I want to say)
**Problem** (optional): problems I faced
**Try** (optional): what I am trying
**TODO** (optional): things to do
**WIP** (optional): work in progress

**Comment by vadasambar** [comment]
## Jan 03 2023
### やったこと
### WIP
- working on the refining the schedule

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github
- [ ] Create an issue around evaluator transposer function doesn't understand json without indentations
    - e.g., for json
        ```
        evalValue before {
                "in": ["@faas.com", {
                  "var": ["email"]
                }]
          }
        evalValue after 
                "in": ["@faas.com", {
                  "var": ["email"]
                }]

        ```

    - for yaml <- needs more info here
      ```
      evalValue before {"in":["@faas.com",{"var":["email"]}]}
      evalValue after "in":["@faas.com",{"var":["email"]}
      ```
Based on print statements just after [this](https://github.com/open-feature/flagd/blob/cef8463a7aff8f48dbc049dcaab86177c3aadd08/pkg/eval/json_evaluator.go#L225) line and after [this](https://github.com/open-feature/flagd/blob/cef8463a7aff8f48dbc049dcaab86177c3aadd08/pkg/eval/json_evaluator.go#L229) line.
 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 04 2023
### やったこと
- created issue for `evaluator transposer function doesn't understand json without indentations`  https://github.com/open-feature/flagd/issues/244
- went through the cluster-autoscaler code to understand https://github.com/kubernetes/autoscaler/issues/5387
### WIP


### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github
 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 05 2023
### やったこと
- watched Keptn vs Keptn lifecycle toolkit video https://www.youtube.com/watch?v=0nCbrG_RFos
### WIP
- https://github.com/keptn-sandbox/datadog-service/issues/140


### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 06 2023
### やったこと

### WIP
- coming up with an approach for https://github.com/kubernetes/autoscaler/issues/5387


### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 09 2023
### やったこと

### WIP
- refining schedule


### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 10 2023
### やったこと
- Wrote a blogpost [`Notes around my failed idea of 'Patching Kubernetes nodes with fixes without restarting the nodes'`](https://vadasambar.com/post/kubernetes/notes-for-executing-script-on-all-nodes/)
- Tweeted about it [here](https://mobile.twitter.com/i/timeline)
### WIP
- Working on the criteria/conditions for writing a blogpost

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 11 2023
### やったこと

### WIP
- PoC around https://github.com/kubernetes/autoscaler/issues/5387 for a generic Lister that can be used for any resource custom or inbuilt

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 12 2023
### やったこと
- Finished PoC around https://github.com/kubernetes/autoscaler/issues/5387 for a generic Lister that can be used for any resource custom or inbuilt. Code sits at https://github.com/vadasambar/dynamic-lister

### WIP

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 13 2023
### やったこと
- Created a draft PR for https://github.com/kubernetes/autoscaler/issues/5387. PR: https://github.com/kubernetes/autoscaler/pull/5419

### WIP

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 16 2023
### やったこと
- adding listers for https://github.com/kubernetes/autoscaler/pull/5419
### WIP
- Refining my schedule

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 17 2023
### やったこと
- refactored code for listers using factory pattern  https://github.com/kubernetes/autoscaler/pull/5419
### WIP
- testing out https://github.com/kubernetes/autoscaler/pull/5419 on a live cluster

### TODO
- [ ] Fix go tests for https://github.com/kubernetes/autoscaler/pull/5419 
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 18 2023
### やったこと

### WIP
- testing out https://github.com/kubernetes/autoscaler/pull/5419 on a live cluster
- fixing failing unit tests for https://github.com/kubernetes/autoscaler/pull/5419

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- cluster-autoscaler [doesn't support GKE](https://github.com/kubernetes/autoscaler/blob/66eb4e9824602e40a487e44a423861d80be75ced/cluster-autoscaler/cloudprovider/builder/builder_all.go#L55-L82). I was trying to run my tests there by deploying a cluster-autoscaler Deployment manually after creating the cluster
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 19 2023
### やったこと
- added fake dynamic listers in unit tests: https://github.com/kubernetes/autoscaler/pull/5419/commits/f8438b15074a8fdc39d68883995ef26a8540817c
### WIP
- fixing failing unit tests for https://github.com/kubernetes/autoscaler/pull/5419

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- cluster-autoscaler [doesn't support GKE](https://github.com/kubernetes/autoscaler/blob/66eb4e9824602e40a487e44a423861d80be75ced/cluster-autoscaler/cloudprovider/builder/builder_all.go#L55-L82). I was trying to run my tests there by deploying a cluster-autoscaler Deployment manually after creating the cluster
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 20 2023
### やったこと
- came up with a criteria for writing blogposts
### WIP
- writing a blogpost 

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- cluster-autoscaler [doesn't support GKE](https://github.com/kubernetes/autoscaler/blob/66eb4e9824602e40a487e44a423861d80be75ced/cluster-autoscaler/cloudprovider/builder/builder_all.go#L55-L82). I was trying to run my tests there by deploying a cluster-autoscaler Deployment manually after creating the cluster
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 23 2023
### やったこと
- participated in today's sig-autoscaling meeting https://github.com/kubernetes/community/tree/master/sig-autoscaling#meetings

### WIP
- refining my schedule

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- cluster-autoscaler [doesn't support GKE](https://github.com/kubernetes/autoscaler/blob/66eb4e9824602e40a487e44a423861d80be75ced/cluster-autoscaler/cloudprovider/builder/builder_all.go#L55-L82). I was trying to run my tests there by deploying a cluster-autoscaler Deployment manually after creating the cluster
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 24 2023
### やったこと
- finished first draft of `suraj3`
- renamed `suraj3` to `kubectl-mo` and made it public: https://github.com/vadasambar/kubectl-mo

### WIP
- working on `suraj4`

### TODO
- [ ] Trying building and deploying the lifecycle-toolkit operator and scheduler on my local machine
- [ ] Working on another blogpost around flagd https://github.com/open-feature/flagd/pull/206/commits/8a38e3c5d30dcbaac5f40c01169b329ca092fa02
- [ ] Finish reading https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking
- [ ] Upload the logo with license and font information in https://github.com/vadafoss/.github

 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- cluster-autoscaler [doesn't support GKE](https://github.com/kubernetes/autoscaler/blob/66eb4e9824602e40a487e44a423861d80be75ced/cluster-autoscaler/cloudprovider/builder/builder_all.go#L55-L82). I was trying to run my tests there by deploying a cluster-autoscaler Deployment manually after creating the cluster THIS MIGHT NOT BE TRUE BECAUSE cluster-autoscaler providers are named after the provider and not after their Kubernetes offerings e..g, aws and not eks
- I don't understand what otel does
- I don't understand how CoreDNS processes queries i.e., which plugin is processed first and in what order?
- datadog-service 1.0.0 integration tests are failing for 0.18.0 https://github.com/keptn-sandbox/datadog-service/actions/runs/3692213775/jobs/6250882507

**Comment by vadasambar** [comment]
## Jan 25 2023
### やったこと

### WIP
- testing https://github.com/kubernetes/autoscaler/pull/5419
- deploying OSS cluster-autoscaler on GKE (working through the permissions issues)

### TODO
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)
 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)

**Comment by vadasambar** [comment]
## Jan 27 2023
### やったこと

### WIP
- working on a blogpost
- understanding how watch function in reflector works

### TODO
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)
 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)

**Comment by vadasambar** [comment]
## Jan 30 2023
### やったこと
- participated in my 2nd sig-autoscaling meeting
### WIP
- refining schedule

### TODO
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)
 
### Problem
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)

**Comment by vadasambar** [comment]
## Jan 31 2023
### やったこと
- replied to review comments in https://github.com/kubernetes/autoscaler/pull/5419
### WIP
- addressing comments in https://github.com/kubernetes/autoscaler/pull/5419
- testing https://github.com/kubernetes/autoscaler/pull/5419

### TODO
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)
 
### Problem
- my code has a problem where [I pass in `Kind` as `Resource` to the GVR](https://github.com/vadasambar/autoscaler/blob/7408206217a907134dde15470f550a47f09eb5cc/cluster-autoscaler/utils/drain/drain.go#L134-L138) in https://github.com/kubernetes/autoscaler/pull/5419 but [that won't work](https://github.com/vadasambar/dynamic-lister/blob/2cffed3120efbd1144a1205382c2294786fc2f7f/main.go#L64-L67) 
- unit tests in utils/drain_test.go are still failing because the scheme is empty and type meta for the objects is empty because of which scheme can't be set in the code either
- check [the Kanban](https://github.com/orgs/vadafoss/projects/3/views/1)
